// <auto-generated />
namespace SharingThesis.Management.Metier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addmemory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmemory));
        
        string IMigrationMetadata.Id
        {
            get { return "202406292039064_add-memory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
